### ISSUE TITLE
Change hitboxes

### ISSUE THREAD

**Issue by magneticflux-** [magneticflux-/fabric-diagonal-panes#4]

**Comment by magneticflux-** [comment]
@FewerFlaws What do you think about the new bounding boxes? The hitboxes are 1x1 resolution and the bounding boxes are 2x2.
![2020-12-22_14 20 14](https://user-images.githubusercontent.com/9124288/102930125-74fa2880-4461-11eb-880c-8b047cbbb9e7.png)

**Comment by FewerFlaws** [comment]
Quite an improvement!  Someone getting close to look out a diagonal window won't be able to see very well, but I don't know whether minecraft allows for diagonal lines in hitboxes at all.  Good work =]

**Comment by magneticflux-** [comment]
Unfortunately, diagonal lines aren't possible without extra dependencies on rendering libraries 😢. I got some more feedback from the Fabric Discord and it seems like a coarser style is more popular.

**Comment by magneticflux-** [comment]
It's coming soon! I just needed to trick `WorldRenderer` with a custom `VoxelShape` subclass that doesn't act normally.

![2020-12-24_14 13 09](https://user-images.githubusercontent.com/9124288/103106362-6bf08f00-45fa-11eb-83f9-7107c31fe53f.png)

**Comment by DearFox** [comment]
This causes me to get stuck on servers without the mod. Add a setting to bring back vanilla hitbox for players on vanilla servers.
